### ISSUE TITLE
hu.dwim.graphviz?

### ISSUE THREAD

**Issue by attila-lendvai** [necto/cl-graphviz#1]
hi!

just a quick question as i have found this while searching for something else... have you checked hu.dwim.graphviz? it's the successor of cl-graphviz, and may already contain the changes you needed.

**Comment by necto** [comment]
Hi, attila-lendvai!
Thank you for the pointer. It is indeed seems as a bit more maintained solution. I mentioned it in the README.md.

**Comment by oxr463** [comment]
See: https://github.com/hu-dwim/hu.dwim.graphviz

**Comment by attila-lendvai** [comment]
honestly, hu.dwim.graphviz should also be updated to use the `c2ffi` based machinery.

i have created an issue to document this: https://github.com/hu-dwim/hu.dwim.graphviz/issues/1
